INSERT INTO customer (name, mobile, email, company, address, description, tags, is_archive)
VALUES 
    ('John Doe', '1234567890', 'john.doe@example.com', 'ABC Company', '123 Main St, City A, Country X', 'Regular customer', 'regular, important', false),
    ('Jane Smith', '9876543210', 'jane.smith@example.com', 'XYZ Corporation', '456 Elm St, City B, Country Y', 'VIP customer', 'VIP, important', false),
    ('Alice Johnson', '5551112222', 'alice.johnson@example.com', '123 Industries', '789 Oak St, City C, Country Z', 'New customer', 'new', false),
    ('Bob Brown', '9998887777', 'bob.brown@example.com', 'Tech Solutions Inc.', '321 Pine St, City D, Country X', 'Returning customer', 'returning, regular', false),
    ('Emma Davis', '7776665555', 'emma.davis@example.com', 'Global Innovations', '654 Cedar St, City E, Country Y', 'Frequent buyer', 'frequent, regular', false),
    ('Michael Wilson', '3332221111', 'michael.wilson@example.com', 'Software Co.', '987 Maple St, City F, Country Z', 'Preferred customer', 'preferred, regular', false),
    ('Sarah Lee', '1112223333', 'sarah.lee@example.com', 'Tech Solutions Inc.', '234 Birch St, City G, Country X', 'First-time buyer', 'new', false),
    ('David Martinez', '4445556666', 'david.martinez@example.com', 'Global Innovations', '876 Walnut St, City H, Country Y', 'Loyal customer', 'loyal, regular', false),
    ('Emily Taylor', '6667778888', 'emily.taylor@example.com', '123 Industries', '543 Pine St, City I, Country Z', 'Satisfied customer', 'satisfied, regular', false),
    ('Chris Rodriguez', '8889990000', 'chris.rodriguez@example.com', 'XYZ Corporation', '765 Oak St, City J, Country X', 'Valued customer', 'valued, regular', false);


CREATE TABLE employees (
    id INT PRIMARY KEY,
    name VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    initial CHAR(1),
    gender VARCHAR(10),
    designation VARCHAR(255),
    degree VARCHAR(255),
    email VARCHAR(255),
    blood_group VARCHAR(10),
    marital_status VARCHAR(20),
    father_name VARCHAR(255),
    mother_name VARCHAR(255),
    city VARCHAR(100),
    current_address VARCHAR(255),
    permanent_address VARCHAR(255),
    education_details TEXT,
    experience_details TEXT,
    health_details TEXT,
    hobbies TEXT,
    description TEXT,
    is_active BOOLEAN,
    is_trainee BOOLEAN,
    joined_date DATE,
    exit_date DATE,
    mobile VARCHAR(20),
    contact_other VARCHAR(20),
    contact_mother VARCHAR(20),
    contact_father VARCHAR(20),
    image BLOB,
    created_by VARCHAR(255),
    created_by_id INT
);
